version: '3.8'
services:
  # mysqldb:
  #   container_name: em-mysql-container
  #   image: mysql:8.0
  #   restart: unless-stopped
  #   volumes:
  #     - $HOME/database:/var/lib/mysql
  #   ports:
  #     - 3306:3306
  #   expose:
  #     - 3306
  #   environment:
  #     MYSQL_DATABASE: elitemente-db
  #     MYSQL_ROOT_PASSWORD: america2020
  #     MYSQL_PASSWORD: password
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysqldb
  #   networks:
  #     - internalnet

  backend:
    build: .
    container_name: em-backend-container
    image: nodeapp:v1
    volumes:
      - $HOME/nodeapp:/code
    ports:
      - '8000:8000'
    expose:
      - 8000
    environment:
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 8000
      DB_HOST: ls-dfcf8968f679b0a019e4891533d6384a3a6a39ef.cbsuayqxzsiq.us-east-2.rds.amazonaws.com
      DB_PORT: 3306
      DB_USER: dbmasteruser
      DB_PASSWORD: HG4OIvvin(gomB>B7%4AZIeBTml`HlXM
      DB_NAME: emdb
      DB_CONNECTION_LIMIT: 10
    #depends_on:
      #- mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
