version: "3.8"
services:
  # mysqldb:
  #   container_name: em-mysql-container
  #   image: mysql:8.0
  #   restart: unless-stopped
  #   volumes:
  #     - $HOME/database:/var/lib/mysql
  #   ports:
  #     - 3306:3306
  #   expose:
  #     - 3306
  #   environment:
  #     MYSQL_DATABASE: elitemente-db
  #     MYSQL_ROOT_PASSWORD: america2020
  #     MYSQL_PASSWORD: password
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysqldb
  #   networks:
  #     - internalnet

  backend:
    build: .
    container_name: vcs-backend-docker
    image: nodeapp:v1
    volumes:
      - $HOME/nodeapp:/code
    ports:
      - "8000:8000"
    expose:
      - 8000
    environment:
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 8000
      DB_HOST: vcs-db-id-instance-1.c1qg6gmznv84.us-east-2.rds.amazonaws.com
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: 'america2020'
      DB_NAME: vishdb
      DB_CONNECTION_LIMIT: 10
    #depends_on:
    #- mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
