version: '3.8'
services:
  backend:
    depends_on:
      - db
    build: .
    env_file: ./.env
    environment:
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASS}'
      DB_NAME: '${DB_NAME}'
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true
  db:
    image: mysql:8.0.30
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASS}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
    volumes:
      - db:/var/lib/mysql
volumes:
  db: